#!/bin/sh
# clean up tl-tester logs after failures
rm log[0-9]*
rm log-[0-9]*
rm log-all*
rm log-combined*
rm val[0-9]*.csv
rm x*.png
rm x*.csv
rm y*.csv
rm y*.out
rm x*.csv.gz
rm y*.out.gz
rm x*.csv.xz
rm j*.json
rm out*-{core,global,socket,thread}
rm perf.data.*.old
rm tlog[0-9]*
rm tltest*_*
rm perf.data*
rm perf[osv]*.csv
rm val.[0-9]*.csv
rm x*.xlsx
rm script[0-9]*
rm toplev[ospv]*.csv toplevm[0-9]*
