#!/bin/sh
# clean up tl-tester logs after failures
rm -f log[0-9]*
rm -f log-[0-9]*
rm -f logsum[0-9]*
rm -f log-all*
rm -f log-combined*
rm -f val[0-9]*.csv
rm -f x*.png
rm -f x*.csv
rm -f y*.csv
rm -f y*.out
rm -f x*.csv.gz
rm -f y*.out.gz
rm -f x*.csv.xz
rm -f j*.json
rm -f out*-{core,global,socket,thread}
rm -f perf.data.*.old
rm -f tlog[0-9]*
rm -f tltest*_*
rm -f perf.data*
rm -f perf*.data.*.old
rm -f perf[osv]*.csv
rm -f val.[0-9]*.csv
rm -f x*.xlsx
rm -f script[0-9]*
rm -f toplev[ospv]*.csv toplevm[0-9]*
rm -f nflog[0-9]*
rm -f toplevs*-cpu*
