#!/bin/sh
# parallel tl-tester run 
# requires GNU parallel

eval `grep -E 'SMTCPUS|NOSMTCPUS' tl-tester | grep -E 'sprmax|lnl-skt'`

( 
echo "RUN='^cpus' ./tl-tester"
for i in $SMTCPUS $NOSMTCPUS ; do
	echo "MATCH=$i RUN=cpus ./tl-tester" 
done
)  | parallel

