#!/bin/sh
# rerun last toplev line from tl-tester log, optionally with a prefix (like python -mpdb)
# tl-tester >& log
# RERUN log python -mpdb
L="$1"
shift
T=$(grep Line.*toplev "$L"  | tail -1 | sed 's/Line [0-9]* //')
echo "$@" $T
eval "$@" $T
