#!/bin/bash
# rerun last toplev line from tl-tester log, optionally with a prefix (like python -mpdb)
# tl-tester >& log
# RERUN log python -mpdb
if [ "x$1" = "x--notltester" ] ; then
	shift
else
	export TL_TESTER=1
fi
L="$1"
shift
T=$(awk '/Line.*FORCE/ { e = e " " $3 } ; /Line.*toplev/ { gsub(/Line [0-9]+ /, ""); print e " " $0; e="" } ' $L | tail -n1)
echo "$@" $T
eval "$@" $T
