#!/bin/sh
# print bottlenecks for all tests in workloads/*
# arguments: to pass to toplev
for i in workloads/* ; do
	[ ! -x "$i" ] && continue
	printf "%-15s " "`basename $i`"
	./toplev "$@" --quiet --single-thread --only-bottleneck -- "$i"
done
