#!/bin/bash
# test different variants of the perf format

set -e
set -x

CMD=${1:-bash -c /bin/true}

[ ! -d data ] && mkdir data

check() { 
	echo -- testing "$@"
	FN=data/perf.$(echo -- "$@" | tr -d '{} ')
	FN=${FN/--/}
	rm -f $FN
	perf record -o $FN "$@" -- $CMD
	if [ $(stat -c %s $FN) == 0 ] ; then
		return
	fi
	python perfdata.py $FN > /dev/null
	python perfpd.py $FN > /dev/null

	# XXX check more fields
	AS=$(python perfdata.py $FN | grep -c SAMPLE)
	BS=$(perf report -i $FN -D | grep -c "PERF_RECORD_SAMPLE")
	[ $AS -eq $BS ]
}

check
check -c 1000
check -g -c 1000
check -b -c 1000
check -b -g fp -c 1000
check -P -c 10000
check -T -c 10003
#check -e cycles:S 
# seems to be broken in perf
#check -e '{cycles,branches}:S'

set +e 
#check -d
check --group -e cycles,branches,branch-misses -c 1000
check -e '{cycles,branches},{branch-misses,cache-misses}'  -c 1000
check -e cycles,branches,branch-misses -c 1000

# new kernel
#check -g dwarf

# XXX sw trace points

