#!/bin/sh
# run all events for 2 seconds each
# requires GNU parallel (http://ftp.gnu.org/gnu/parallel/)
./ucevent.py --unsupported --broken --name-only > all-events
parallel --no-notice --halt 1 "$@" -n 1 -k < all-events sh -c "echo "EVENT" {} ; $WRAP ./ucevent.py -v {} sleep 2.2"
