#!/bin/sh
# requires GNU parallel (http://ftp.gnu.org/gnu/parallel/)
./ucevent.py --name-only > derived-events
parallel --no-notice --halt 1 "$@" -n 1 -k < derived-events sh -c "echo "EVENT" {} ; $WRAP ./ucevent.py -v {} sleep 2.2"
