#!/bin/sh
export FORCECPU=${FORCECPU:-hsx}
./ucevent.py --mock --unsupported --broken --name-only > all-events
parallel --halt 1 --no-notice "$@" -n 1 -k < all-events sh -c "echo "EVENT" {} ; $WRAP ./ucevent.py --mock -v {}"

