#!/bin/sh

CPULIST="${CPULIST:-jkt ivt hsx bdxde bdx skx}"

for cpu in $CPULIST ; do

export FORCECPU=$cpu

for i in CHECK-* SANITY-ALL MOCK-ALL ; do 
	echo $i 
	./$i
	echo STATUS $?
done

./uctester | tee res-tester


done
