#!/bin/sh
# run all events for 2 seconds each
# requires GNU parallel (http://ftp.gnu.org/gnu/parallel/)
EXTRA=""
[ -n "$MOCK" ] && EXTRA=--mock
./ucevent.py --unsupported --broken --name-only > all-events
parallel --no-notice --halt 1 "$@" -n 1 -k < all-events sh -c "echo "EVENT" {} ; $WRAP ./sanity-run.py $EXTRA -v {} sleep 2.2"
