#!/bin/sh
set -e
if [ ! -f tramp3d-v4.cpp ] ; then
	echo "Downloading tramp3d-v4"
	curl https://raw.githubusercontent.com/microsoft/checkedc-llvm-test-suite/master/MultiSource/Benchmarks/tramp3d-v4/tramp3d-v4.cpp |
	sed -e 's/mutable Element_t/Element_t/' \
	    -e 's/mutable Pooma::Iterate_t/Pooma::Iterate_t/' > tramp3d-v4.cpp
fi
g++ -w -std=gnu++11 tramp3d-v4.cpp
